"""Checkpoints CP8: the store for inspection outcomes.

The first piece of state in this app that is NOT rebuildable -- a human
judgement that exists nowhere else and cannot be regenerated by
build_snapshot(). That is why this lives in its own SQLite file rather than
in data/snapshot/ (Parquet, fully rebuilt every run) or data/raw/ (the
acquisition ladder's cache, also rebuildable from the live source in
principle). Nothing in build_snapshot.py imports this module, and it must
stay that way: a rebuild that could reach this file could also overwrite it.

SQLite chosen over an append-only Parquet or JSONL file specifically for a
native uniqueness constraint -- see contracts/inspection_outcome.schema.json
and Checkpoints.md CP8 (eng review, 2026-09-05) for the reasoning. It is
Python stdlib: no new dependency.

Outside-voice correction, round 2 (2026-09-05, same session): the original
UNIQUE(work_id, inspected_on) picked "rejected" when Checkpoints CP8's own
wording allows "rejected or explicitly versioned", and blocked a real case
(agency_unresponsive in the morning, a real inspection that same afternoon).
The table now has a surrogate outcome_id primary key, UNIQUE(work_id,
inspected_on, inspector_id) -- so the same inspector double-submitting the
same work on the same date is still rejected, which was the actual scenario
the original constraint protected against -- and a nullable `supersedes`
column so a later entry can explicitly amend an earlier one instead of the
storage layer refusing a legitimate second visit.

F-01 (nemotronreview.md): rows now carry implementing_district_authority
(IDA_NAME) and implementing_agency (IA_NAME) separately, plus a
context_version column. Rows written before that split have their old
implementing_agency value (which held IDA_NAME) reported under
implementing_district_authority on read; their stored values are never
rewritten. See _migrate_f01_columns() and _row_to_dict().
"""

from __future__ import annotations

import contextlib
import json
import sqlite3
from pathlib import Path
from typing import Any

# outcomes/store.py -> parents[4] is "05-App/". Same depth as
# ingest/mplads_adapter.py, which anchors the same way.
_APP_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_DB_PATH = _APP_ROOT / "data" / "outcomes" / "outcomes.db"
_SCHEMA_PATH = _APP_ROOT / "contracts" / "inspection_outcome.schema.json"

# Columns a caller supplies. outcome_id is deliberately absent: it is a
# surrogate key SQLite assigns on insert (INTEGER PRIMARY KEY, aliases
# rowid), never chosen by the caller.
_INSERT_COLUMNS = (
    "work_id",
    "inspected_on",
    "outcome",
    "notes",
    "inspector_id",
    "state",
    "constituency",
    "implementing_district_authority",
    "implementing_agency",
    "work_category",
    "sanctioned_amount_inr",
    "inspection_rank_at_time",
    "risk_score_at_time",
    "cutoff_rank_at_time",
    "population_n_at_time",
    "in_control_sample",
    "supersedes",
    "context_version",
)

# Full column set, in select order. outcome_id first: it's the row's own
# identity, and every read helper returns it so a caller can later name a
# specific outcome as the target of a `supersedes` amendment.
_COLUMNS = ("outcome_id", *_INSERT_COLUMNS)

_BOOL_COLUMNS = ("in_control_sample",)

# F-01 (nemotronreview.md): what the two agency-shaped context columns mean.
#   1 = written before the IDA/IA split. implementing_agency held IDA_NAME
#       (the District Authority) and implementing_district_authority did not
#       exist. Every row that predates the migration below reads as 1.
#   2 = implementing_district_authority is IDA_NAME and implementing_agency
#       is IA_NAME (null when unknown). Every new row is written as 2.
_CONTEXT_VERSION = 2


class OutcomeError(Exception):
    """Base class for every error this module raises."""


class UnknownOutcomeEnumError(OutcomeError):
    """`outcome` is not one of the frozen enum values in
    contracts/inspection_outcome.schema.json. Raised before any database
    write is attempted -- an invalid enum value never reaches the DB layer,
    so a bug here can never look like a constraint violation.
    """


class DuplicateOutcomeError(OutcomeError):
    """The same inspector already recorded an outcome for this work on this
    date. Checkpoints CP8: rejected, not silently overwritten or
    double-counted. A DIFFERENT inspector, or the same inspector on a
    different visit recorded as an explicit `supersedes` amendment, is not
    a duplicate -- see the module docstring.
    """


def _valid_outcomes() -> frozenset[str]:
    """Read fresh from the schema file every call rather than caching at
    import time -- the schema is the single source of truth (same
    discipline contracts/validate.py and risk/engine.py already follow), so
    a future edit to the enum takes effect without restarting the process.
    """
    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    return frozenset(schema["properties"]["outcome"]["enum"])


def issue_mapping() -> dict[str, bool | None]:
    """Outside-voice correction, 2026-09-05: the enum-to-"had an issue"
    mapping is a second free parameter precision-at-quota needs, frozen
    here rather than chosen after real results exist. true = counts as an
    issue, false = counts as no issue, null/None = inconclusive, excluded
    from the denominator entirely (see
    contracts/inspection_outcome.schema.json's _issue_mapping for the
    reasoning per value). Read fresh each call, same reason as
    _valid_outcomes().
    """
    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    # Underscore-prefixed keys are documentation, not enum values -- same
    # convention contracts/strings.json uses throughout (_meta, _note, etc).
    return {k: v for k, v in schema["_issue_mapping"].items() if not k.startswith("_")}


def init_db(db_path: Path | None = None) -> None:
    """Creates the outcomes table if it doesn't exist yet. Safe to call on
    every process start (api/main.py's startup hook, the same pattern
    api/snapshot.py's bootstrap_if_needed already uses) -- CREATE TABLE IF
    NOT EXISTS never touches existing rows.
    """
    db_path = db_path or DEFAULT_DB_PATH
    db_path.parent.mkdir(parents=True, exist_ok=True)
    with contextlib.closing(sqlite3.connect(db_path)) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS inspection_outcomes (
                outcome_id INTEGER PRIMARY KEY AUTOINCREMENT,
                work_id TEXT NOT NULL,
                inspected_on TEXT NOT NULL,
                outcome TEXT NOT NULL,
                notes TEXT NOT NULL,
                inspector_id TEXT NOT NULL,
                state TEXT NOT NULL,
                constituency TEXT NOT NULL,
                implementing_district_authority TEXT,
                implementing_agency TEXT,
                work_category TEXT NOT NULL,
                sanctioned_amount_inr REAL NOT NULL,
                inspection_rank_at_time INTEGER NOT NULL,
                risk_score_at_time REAL NOT NULL,
                cutoff_rank_at_time INTEGER NOT NULL,
                population_n_at_time INTEGER NOT NULL,
                in_control_sample INTEGER NOT NULL,
                supersedes INTEGER,
                context_version INTEGER NOT NULL DEFAULT 1,
                UNIQUE(work_id, inspected_on, inspector_id),
                FOREIGN KEY (supersedes) REFERENCES inspection_outcomes(outcome_id)
            )
            """
        )
        _migrate_f01_columns(conn)
        conn.commit()


def _migrate_f01_columns(conn: sqlite3.Connection) -> None:
    """Adds the F-01 columns to a table created before them. Idempotent.

    Existing rows keep every stored value byte for byte. ADD COLUMN with
    DEFAULT 1 marks them as context_version 1, which _row_to_dict reads with
    their original meaning. Only the inspection_outcomes table is touched:
    the R-06 alias tables that share this SQLite file are never altered.
    """
    columns = {row[1] for row in conn.execute("PRAGMA table_info(inspection_outcomes)")}
    if "implementing_district_authority" not in columns:
        conn.execute(
            "ALTER TABLE inspection_outcomes ADD COLUMN implementing_district_authority TEXT"
        )
    if "context_version" not in columns:
        conn.execute(
            "ALTER TABLE inspection_outcomes "
            "ADD COLUMN context_version INTEGER NOT NULL DEFAULT 1"
        )


def record_outcome(
    work_id: str,
    inspected_on: str,
    outcome: str,
    notes: str,
    inspector_id: str,
    state: str,
    constituency: str,
    implementing_agency: str | None,
    work_category: str,
    sanctioned_amount_inr: float,
    inspection_rank_at_time: int,
    risk_score_at_time: float,
    cutoff_rank_at_time: int,
    population_n_at_time: int,
    in_control_sample: bool,
    *,
    implementing_district_authority: str | None,
    supersedes: int | None = None,
    db_path: Path | None = None,
) -> int:
    """Writes one outcome, returns its new outcome_id. Raises
    UnknownOutcomeEnumError for an outcome outside the frozen enum (checked
    in Python before the DB is touched) and DuplicateOutcomeError for a
    repeat (work_id, inspected_on, inspector_id) triple (checked by the DB's
    own UNIQUE constraint -- real enforcement, not a check-then-write race).

    Every "_at_time" argument, in_control_sample, and the denormalized
    context fields (state/constituency/implementing_agency/work_category/
    sanctioned_amount_inr) are the caller's responsibility to supply as the
    CURRENT values at the moment of recording -- this function does not
    look any of them up, because doing so here would silently reintroduce
    the live-join bug this design specifically avoids (see the module
    docstring, Checkpoints CP8, and the schema's _outside_voice_corrections
    round 1 for cutoff_rank_at_time / population_n_at_time, round 2 for why
    the context fields are denormalized at all: work_id "stability across
    pulls" is asserted, never observed, so an orphaned outcome must stay
    human-readable without a live join back to a work that may no longer
    resolve).

    `supersedes`, when given, must be an existing outcome_id -- this
    function does not validate that beyond the database's own FOREIGN KEY
    (SQLite only enforces it when the caller has turned on
    `PRAGMA foreign_keys`, which this module does not; treated as
    advisory, not enforced, for a single-officer prototype with no
    concurrent-amendment race to guard against).
    """
    if outcome not in _valid_outcomes():
        raise UnknownOutcomeEnumError(
            f"{outcome!r} is not a valid inspection outcome. Valid values: "
            f"{sorted(_valid_outcomes())}"
        )

    values = {
        "work_id": work_id,
        "inspected_on": inspected_on,
        "outcome": outcome,
        "notes": notes,
        "inspector_id": inspector_id,
        "state": state,
        "constituency": constituency,
        "implementing_district_authority": implementing_district_authority,
        "implementing_agency": implementing_agency,
        "work_category": work_category,
        "sanctioned_amount_inr": sanctioned_amount_inr,
        "inspection_rank_at_time": inspection_rank_at_time,
        "risk_score_at_time": risk_score_at_time,
        "cutoff_rank_at_time": cutoff_rank_at_time,
        "population_n_at_time": population_n_at_time,
        # SQLite has no native boolean; stored as 0/1, converted back to
        # bool on read in _row_to_dict.
        "in_control_sample": int(in_control_sample),
        "supersedes": supersedes,
        "context_version": _CONTEXT_VERSION,
    }

    db_path = db_path or DEFAULT_DB_PATH
    init_db(db_path)
    with contextlib.closing(sqlite3.connect(db_path)) as conn:
        try:
            cursor = conn.execute(
                f"INSERT INTO inspection_outcomes ({', '.join(_INSERT_COLUMNS)}) "
                f"VALUES ({', '.join('?' for _ in _INSERT_COLUMNS)})",
                tuple(values[col] for col in _INSERT_COLUMNS),
            )
            conn.commit()
            return cursor.lastrowid
        except sqlite3.IntegrityError as exc:
            raise DuplicateOutcomeError(
                f"inspector {inspector_id!r} already recorded an outcome for "
                f"work_id={work_id!r} on {inspected_on!r}; rejected rather "
                "than overwritten. Record an explicit supersedes amendment "
                "instead if this is meant to correct that entry."
            ) from exc


def _row_to_dict(row: tuple[Any, ...]) -> dict[str, Any]:
    record = dict(zip(_COLUMNS, row, strict=True))
    for column in _BOOL_COLUMNS:
        record[column] = bool(record[column])
    if record["context_version"] == 1:
        # Written before F-01: this row's implementing_agency column holds
        # IDA_NAME. Report it under the field that means District Authority
        # and leave the true agency unknown instead of repeating the
        # mislabel. The stored values themselves are never rewritten.
        record["implementing_district_authority"] = record["implementing_agency"]
        record["implementing_agency"] = None
    return record


def get_outcomes_for_work(work_id: str, *, db_path: Path | None = None) -> list[dict[str, Any]]:
    """Every recorded outcome for one work, oldest first. Empty list, not an
    error, when the work has never been inspected.
    """
    db_path = db_path or DEFAULT_DB_PATH
    init_db(db_path)
    with contextlib.closing(sqlite3.connect(db_path)) as conn:
        rows = conn.execute(
            f"SELECT {', '.join(_COLUMNS)} FROM inspection_outcomes "
            "WHERE work_id = ? ORDER BY inspected_on ASC",
            (work_id,),
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def list_all_outcomes(*, db_path: Path | None = None) -> list[dict[str, Any]]:
    """Every outcome ever recorded. This is precision-at-quota's only input:
    it groups these by inspection_rank_at_time against the quota cutoff at
    the time each was recorded, never against the live current rank.
    """
    db_path = db_path or DEFAULT_DB_PATH
    init_db(db_path)
    with contextlib.closing(sqlite3.connect(db_path)) as conn:
        rows = conn.execute(
            f"SELECT {', '.join(_COLUMNS)} FROM inspection_outcomes ORDER BY inspected_on ASC"
        ).fetchall()
    return [_row_to_dict(row) for row in rows]
